### ISSUE TITLE
Settings should raise readable errors

### ISSUE THREAD

**Issue by GDWR** [GDWR/DiscordArena#1]
I am wanting the `settings.py` for the Bot to validate required environment variables if specified. \
Here is an example of how the `settings.py` should look like.

Using a pre-made module like `Dynaconf` etc for this is also acceptable.

This would most likely be used on the Website also.

```py
# If these environment variables are not found, an `EnvironmentError` or similar should be raise 
# with an explicit error of what is missing.
TOKEN = setting("TOKEN", required=True)
API_URL = setting("API_URL", required=True)

# If a second positional argument is passed, it should be the default if the first var is not found.
EMBED_COLOUR = settings("EMBED_COLOUR", "FFA500")
```

**Comment by Slushs** [comment]
Wouldn't be hard at all I can do that right now if you would like?

**Comment by DudeBro249** [comment]
I've also come up with a fix for this issue in [this pull request](https://github.com/GDWR/DiscordArena/pull/4)

**Comment by DudeBro249** [comment]
This issue can be closed now right? [This PR](https://github.com/GDWR/DiscordArena/pull/4) has been merged.

**Comment by DudeBro249** [comment]
Should this pull request be closed?
