### ISSUE TITLE
Use DiscordSlash commands for the bot.

### ISSUE THREAD

**Issue by GDWR** [GDWR/DiscordArena#10]
It is best to catch this before any development on the bot so we can approach it as a webhook. 
Playing into a webhook allows us to run this alongside the FastAPI.

For this, I want all the current commands on the bot converted to DiscordSlash commands.
This will overwrite the current implementation.

**Comment by Slushs** [comment]
Currently, we need to figure out what we are gonna do. We can either use the LIB or do it by hand. Using the discord.py addon will be very easy and not really with any downsides. But using the webhook might long side the FastAPI might be nicer but we will have to talk about it.
