### ISSUE TITLE
uvicorn is not in req.txt

### ISSUE THREAD

**Issue by Slushs** [GDWR/DiscordArena#12]
Uvicorn is not in the req.txt file so whenever you clone the repo and install the req.txt file uvicorn doesn't get installed. Its a simple fix, just wanted to document it.

**Comment by DudeBro249** [comment]
If you install anything with `pip` within your virtual environment, make sure to run `pip freeze > requirements.txt` to update the requirements.txt file based on the installed packages in your virtual environment. This will ensure that everybody gets the latest packages whenever they clone/pull the repository.
