### ISSUE TITLE
Player Inventory

### ISSUE THREAD

**Issue by GDWR** [GDWR/DiscordArena#21]
Create a Table for Items so we can have player "inventories"

I'd recommend having a basic table for now like below

__Item Table__
| id  | name         | owner                           | value | rarity |
| :--: | :----------: | :-----------------------: | :----:  | :---: |
| 1 | GreatSword | 107226564030156800 | 500   | 3 |
| 2 | AxeBore | 481064298932731915 | 788 | 5 |
| ... | ... | ... | ... | ... |

This will be added to and changed in the future but will work for the beginning phases.

What needs to be done:
* Create Item Table / ORM Class
* API endpoint to add Item.
* API endpoint to get an Item by ID.
* API endpoint to get all Items owned by a player.
* Bot commands to create a Item
* Bot commands to get an item using ID
* Bot commands to get all your items.

**Comment by DudeBro249** [comment]
I would like to be assigned to this.

**Comment by GDWR** [comment]
I'll be doing the Discord side
