### ISSUE TITLE
OpenChests

### ISSUE THREAD

**Issue by GDWR** [GDWR/DiscordArena#27]
We want the ability for players to open Chests.

In the future, we will want to have different rarities of chests and also a check that the user trying has a chest.

For now, what will want for these issues is:

API
---
Add a type column to the Item table too allow us to determine Type of Item.

e.g.
```py
class Type(Enum):
    Chest = 1
    Weapon = 2
```

__Item Table__
| id  | name         | owner                           | value | rarity | type |
| :--: | :----------: | :-----------------------: | :----:  | :---: | :--: |
| 1 | GreatSword | 107226564030156800 | 500   | 3 | 2 |
| 2 | AxeBore | 481064298932731915 | 788 | 5 | 2 |
| 3 | Chest | 107226564030156800  | 200 | 2 | 1
| ... | ... | ... | ... | ... | ... |

Make an endpoint to open a chest, this should accept the `item_id`,
Validate it is a chest -> Generate an Item (using the same ID) -> return the item.

Bot
---
Add a slash command for opening chests.
`/open chest <chest_id>`

---

This is an example of how this could be done. 
If you find it appropriate to use a different table or even just a number on the `Player` table.
i.e.
__Player Table__
| id  | display_name | join_date | chests |
| :-:  | :------------:  | :--------: | :-----: |
| 107226564030156800 | Griff | 2021-04-18 11:28:02.016160 | 3 |
| 481064298932731915 | Jake | 2021-04-19 11:28:02.016160 | 0 |
| ... | ... | ... | ... |

Let me know how you are going to approach this.

**Comment by DudeBro249** [comment]
@KJ002 worked on and merged this feature into the main branch, so I think issue can be closed. @GDWR what do you think?
