### ISSUE TITLE
Join command doesn't work

### ISSUE THREAD

**Issue by GDWR** [GDWR/DiscordArena#28]
I don't have any clue what the issue is.
But when trying to use the Join command `/join`
This is sent back.
`Invalid interaction application command`

![image](https://user-images.githubusercontent.com/57012020/115152297-767eda80-a068-11eb-8618-c9c6a346d2e4.png)

I am unsure if this is our implementation causing this, The `discord-py-slash-commands` or even the DiscordAPI itself.

**Comment by Slushs** [comment]
I will look into this, might be a problem with the API if nothing was changed on the bot. But I will check and see if I can recreate the error.

**Comment by GDWR** [comment]
I would hold off, looks like we will transition into using webhooks

**Comment by DudeBro249** [comment]
We will be sticking with regular discord commands now so I think this issue can be closed yes? @GDWR What do you think?
