### ISSUE TITLE
Basic Logging

### ISSUE THREAD

**Issue by GDWR** [GDWR/DiscordArena#33]
Set up logging for the project that can be used across the bot.
Nice log formatting, i.e. `(Datetime) - [logger_name]: message`

**Comment by GDWR** [comment]
Also, 
- sprinkle some logging for the database connection and discord bot connection to begin with.
- Add `LOG_LEVEL` environment var for easy changing of the log level.

**Comment by KJ002** [comment]
Solved by #38
